ci: Try to fix test failure during pip install
During nightly tests we get an error related to babel API missing CompileCatalog.

Try to force upgrade via pip to avoid the error, we cannot reproduce this in
our Dockerfile with the same ubuntu image, so cross fingers.

    Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3/dist-packages (from simplesat>=0.9.1->fusesoc) (21.2.0)
    Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from simplesat>=0.9.1->fusesoc) (1.16.0)
    Collecting okonomiyaki>=0.16.6
      Downloading okonomiyaki-3.0.0-py2.py3-none-any.whl (8.4 MB)
	 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 91.6 MB/s eta 0:00:00
    Requirement already satisfied: babel<3,>=2 in /usr/lib/python3/dist-packages (from jsonschema2md->fusesoc) (2.8.0)
    Collecting markdown<4,>=3
      Downloading markdown-3.8.2-py3-none-any.whl (106 kB)
	 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 KB 43.3 MB/s eta 0:00:00
    Building wheels for collected packages: jsonschema2md
      Building wheel for jsonschema2md (pyproject.toml): started
      Building wheel for jsonschema2md (pyproject.toml): finished with status 'error'
      error: subprocess-exited-with-error

      × Building wheel for jsonschema2md (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [24 lines of output]
	  Traceback (most recent call last):
	    File "/tmp/pip-install-cwh7nnwc/jsonschema2md_e5d0c3257472410eb85080c0284e4c94/scripts/build.py", line 7, in <module>
	      from babel.messages.frontend import CompileCatalog